function                                                                     ...
generateConvertGeodeticToEcefPurposeMessage(  )
%{------------------------------------------------------------------------------
   STDOUT = 1;
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   fprintf                                                                   ...
   (                                                                         ...
     STDOUT,                                                                 ...
     [                                                                       ...
       '\n\n\n'                                                              ...
       '%s%s\n'                                                              ...
       '%s\n%s\n%s\n%s\n%s\n'                                                ...
       '%s%s\n'                                                              ...
       '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                                ...
       '%s%s\n'                                                              ...
       '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                            ...
       '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                            ...
       '%s\n%s\n%s\n%s\n%s\n%s\n'                                            ...
       '%s%s\n'                                                              ...
       '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                            ...
       '%s\n%s\n%s\n%s\n%s\n'                                                ...
       '%s%s\n'                                                              ...
       '%s\n%s\n%s\n%s\n%s\n'                                                ...
       '%s%s\n'                                                              ...
       '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                            ...
       '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                            ...
       '%s%s\n'                                                              ...
       '\n\n\n'                                                              ...
     ],                                                                      ...
     '====================================================================', ...
     '===========',                                                          ...
     '|',                                                                    ...
     '|  FUNCTION:',                                                         ...
     '|',                                                                    ...
     '|    convertConvertGeodeticToEcefGeodeticToEcef',                      ...
     '|',                                                                    ...
     '|-------------------------------------------------------------------', ...
     '-----------',                                                          ...
     '|',                                                                    ...
     '|  PURPOSE:',                                                          ...
     '|',                                                                    ...
     '|    Convert:',                                                        ...
     '|      Geodetic   North Latitude,',                                    ...
     '|      Geocentric East  Longitude',                                    ...
     '|      Geodetic   Altitude',                                           ...
     '|    to Earth Centered Earth Fixed (ECEF) rectangular coordinates.',   ...
     '|',                                                                    ...
     '|-------------------------------------------------------------------', ...
     '-----------',                                                          ...
     '|',                                                                    ...
     '|  INPUTS:',                                                           ...
     '|',                                                                    ...
     '|    earthEquatorialRadiusMeters',                                     ...
     '|      Length of Earth equatorial radius',                             ...
     '|      Also length of Earth ellipsoid semi-major axis.',               ...
     '|      Units:  [meters]',                                              ...
     '|',                                                                    ...
     '|    earthEllipsoidalEccentricitySquared',                             ...
     '|      Earth ellipsoid eccentricity squared.',                         ...
     '|      Units:  [nondimensional]',                                      ...
     '|',                                                                    ...
     '|    geodeticNorthLatitudeRadians',                                    ...
     '|      The geodetic North latitude.',                                  ...
     '|      Northern hemisphere is positive.',                              ...
     '|      Units:  [radians]',                                             ...
     '|',                                                                    ...
     '|    geocentricEastLongitudeRadians',                                  ...
     '|      The geocentric East longitude.',                                ...
     '|      Eastward is positive.',                                         ...
     '|      Units:  [radians]',                                             ...
     '|',                                                                    ...
     '|    geodeticAltitudeMeters',                                          ...
     '|      The geodetic altitude above the specified reference ellipsoid.',...
     '|      Units:  [meters]',                                              ...
     '|',                                                                    ...
     '|-------------------------------------------------------------------', ...
     '-----------',                                                          ...
     '|',                                                                    ...
     '|  OUTPUT:',                                                           ...
     '|',                                                                    ...
     '|    xRectangularMeters',                                              ...
     '|      The Earth Centered Earth Fixed (ECEF) X Rectangular position',  ...
     '|      Units:  [meters].',                                             ...
     '|',                                                                    ...
     '|    yRectangularMeters',                                              ...
     '|      The Earth Centered Earth Fixed (ECEF) Y Rectangular position',  ...
     '|      Units:  [meters].',                                             ...
     '|',                                                                    ...
     '|    zRectangularMeters',                                              ...
     '|      The Earth Centered Earth Fixed (ECEF) Z Rectangular position',  ...
     '|      Units:  [meters].',                                             ...
     '|',                                                                    ...
     '|-------------------------------------------------------------------', ...
     '-----------',                                                          ...
     '|',                                                                    ...
     '|  RETURNED VALUE:',                                                   ...
     '|',                                                                    ...
     '|    None.',                                                           ...
     '|',                                                                    ...
     '|-------------------------------------------------------------------', ...
     '-----------',                                                          ...
     '|',                                                                    ...
     '|  REFERENCE(s):',                                                     ...
     '|',                                                                    ...
     '|    [ 1 ]  "Geographic coordinate conversion",',                      ...
     '|           "Coordinate system conversion",',                          ...
     '|           "From geodetic to ECEF coordinates"',                      ...
     '|           https://en.wikipedia.org/wiki/Geographic_coordinate_',     ...
     '|           conversion',                                               ...
     '|',                                                                    ...
     '|    [ 2 ]  "Geometric Geodesy, Part A",',                             ...
     '|           "A set of lecture notes which are an introduction to',     ...
     '|            ellipsoidal geometry related to geodesy.",',              ...
     '|            R. E. Deakin and M. N. Hunter,',                          ...
     '|            School of Mathematical and Geospatial Sciences,',         ...
     '|            RMIT University,',                                        ...
     '|            Melbourne, Australia,',                                   ...
     '|            January 2013',                                            ...
     '|            www.mygeodesy.id.au/documents/Geometric%20Geodesy%20A',   ...
     '|                                          (2013).pdf',                ...
     '|',                                                                    ...
     '====================================================================', ...
     '==========='                                                           ...
   );
%------------------------------------------------------------------------------- 
   return;
%}------------------------------------------------------------------------------
