function
generateConvertGeodeticToEcefPurposeMessage(  )
#-------------------------------------------------------------------------------
#        1         2         3         4         5         6         7         8
#2345678901234567890123456789012345678901234567890123456789012345678901234567890
#-------------------------------------------------------------------------------

#{------------------------------------------------------------------------------
   formatString =
   string(
           "\n\n\n",
           "%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n",
           "%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n",
           "%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n",
           "%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n",
           "%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n",
           "%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n",
           "%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n",
           "%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n",
           "%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n",
           "\n\n\n"
         );
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   printFormatted(
      stdout,
      formatString,
      "====================================================================",
      "|",
      "|  FUNCTION:",
      "|    convertGeodeticToEcef",
      "|",
      "|-------------------------------------------------------------------",
      "|",
      "|  PURPOSE:",
      "|",
      "|    Convert:",
      "|      Geodetic   Latitude,",
      "|      Geocentric Longitude",
      "|      Geodetic   Altitude",
      "|    to Earth Centered Earth Fixed (ECEF) rectangular coordinates.",
      "|",
      "|-------------------------------------------------------------------",
      "|",
      "|  INPUTS:",
      "|",
      "|     earthEquatorialRadiusMeters",
      "|       Length of Earth equatorial radius",
      "|       Also length of Earth ellipsoid semi-major axis.",
      "|       UNITS:  [meters]",
      "|",
      "|     earthEllipsoidalEccentricitySquared",
      "|       Earth ellipsoid eccentricity squared.",
      "|       UNITS:  [nondimensional]",
      "|",
      "|     geodeticNorthLatitudeRadians",
      "|       The North geodetic latitude.",
      "|       Northern hemisphere is positive.",
      "|       UNITS:  [radians]",
      "|",
      "|     geocentricEastLongitudeRadians",
      "|       The East Geocentric longitude.",
      "|       Eastward is positive.",
      "|       UNITS:  [radians]",
      "|",
      "|     geodeticAltitudeMeters",
      "|       The geodetic altitude above the specified reference",
      "|       ellipsoid.",
      "|       UNITS:  [meters]",
      "|",
      "|-------------------------------------------------------------------",
      "|",
      "|  OUTPUT:",
      "|",
      "|    None.",
      "|",
      "|-------------------------------------------------------------------",
      "|",
      "|  RETURNED VALUE:",
      "|",
      "|    A vector of length 3 which contains:",
      "|",
      "|      [ 1 ]  rXEcefMeters",
      "|             The X ECEF position.",
      "|             UNITS:  [meters]",
      "|",
      "|      [ 2 ]  rYEcefMeters",
      "|             The Y ECEF position.",
      "|             UNITS:  [meters]",
      "|",
      "|      [ 3 ]  rZEcefMeters",
      "|             The Z ECEF position.",
      "|             UNITS:  [meters]",
      "|",
      "|-------------------------------------------------------------------",
      "|",
      "|  REFERENCE(s):",
      "|",
      "|     [ 1 ]  'Geographic coordinate conversion',",
      "|            'Coordinate system conversion',",
      "|            'From geodetic to ECEF coordinates'",
      "|            https://en.wikipedia.org/wiki/",
      "|            Geographic_coordinate_conversion",
      "|",
      "|     [ 2 ]  'Geometric Geodesy, Part A',",
      "|            'A set of lecture notes which are an introduction",
      "|             to ellipsoidal geometry related to geodesy.',",
      "|            R. E. Deakin and M. N. Hunter,",
      "|            School of Mathematical and Geospatial Sciences,",
      "|            RMIT University,",
      "|            Melbourne, Australia,",
      "|            January 2013",
      "|            www.mygeodesy.id.au/documents/Geometric%20Geodesy",
      "|            %20A(2013).pdf",
      "|",
      "===================================================================="
    );
#-------------------------------------------------------------------------------
   return;
#-------------------------------------------------------------------------------
   end;
#}------------------------------------------------------------------------------
