function                                                                     ...
generateTestProgramOutputHeader                                              ...
        (                                                                    ...
          specifiedFixedTrueEastGeocentricLongitudeDegrees                   ...
        )
%{------------------------------------------------------------------------------
%
%  Header for Output
%
%-------------------------------------------------------------------------------
   STDOUT = 1;
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   fprintf                                                                   ...
    (                                                                        ...
      STDOUT,                                                                ...
      [                                                                      ...
        '\n\n\n'                                                             ...
        '%s%s\n'                                                             ...
        '%s\n'                                                               ...
        '%s\n'                                                               ...
        '%s%s\n'                                                             ...
        '%s\n'                                                               ...
        '%s\n'                                                               ...
        '%s\n'                                                               ...
      ],                                                                     ...
      '============================================',                        ...
      '============================================',                        ...
      '|',                                                                   ...
      '| EARTH-CENTERED EARTH-FIXED (ECEF) RECTANGULAR COORDINATES',         ...
      '| TO GEODETIC CONVERSIONS USING THIRD ORDER',                         ...
      ' HALLEY''S ITERATIVE METHOD',                                         ...
      '| ONLY ONE HALLEY''s ITERATION IS USED TO ACHIEVE NEAR',              ...
      '| DOUBLE PRECISION ACCURACY.',                                        ...
      '|'                                                                    ...
    );
   fprintf                                                                   ...
    (                                                                        ...
      STDOUT,                                                                ...
      [                                                                      ...
      '%s%s\n'                                                               ...
      '%s\n'                                                                 ...
      '%s%+12.4f%s\n'                                                        ...
      '%s\n'                                                                 ...
      '%s%s\n'                                                               ...
      ],                                                                     ...
      '|-------------------------------------------',                        ...
      '--------------------------------------------',                        ...
      '|',                                                                   ...
      '| True Geocentric East Longitude:-->',                                ...
      specifiedFixedTrueEastGeocentricLongitudeDegrees,                      ...
      ' [degrees]',                                                          ...
      '|',                                                                   ...
      '|===========================================',                        ...
      '============================================'                         ...
    );
   fprintf                                                                   ...
    (                                                                        ...
      STDOUT,                                                                ...
      '%s%s%s\n',                                                            ...
      '|                   ',                                                ...
      '|                  ',                                                 ...
      '|    GEODETIC CONVERSION ERROR RESULTS   '                            ...
    );
   fprintf                                                                   ...
    (                                                                        ...
      STDOUT,                                                                ...
      '%s%s%s%s\n',                                                          ...
      '|  True             ',                                                ...
      '|                  ',                                                 ...
      '|--------------------',                                               ...
      '---------------------'                                                ...
    );
   fprintf                                                                   ...
    (                                                                        ...
      STDOUT,                                                                ...
      '%s%s%s%s\n',                                                          ...
      '|  Geodetic         ',                                                ...
      '|  True            ',                                                 ...
      '|  Delta             ',                                               ...
      '|   Delta'                                                            ...
    );
   fprintf                                                                   ...
    (                                                                        ...
      STDOUT,                                                                ...
      '%s%s%s%s\n',                                                          ...
      '|  North            ',                                                ...
      '|  Geodetic        ',                                                 ...
      '|  Geodetic          ',                                               ...
      '|   Geodetic'                                                         ...
    );
   fprintf                                                                   ...
    (                                                                        ...
      STDOUT,                                                                ...
            '%s%s%s%s\n',                                                    ...
      '|  Latitude         ',                                                ...
      '|  Altitude        ',                                                 ...
      '|  Latitude          ',                                               ...
      '|   Altitude'                                                         ...
    );
   fprintf                                                                   ...
    (                                                                        ...
      STDOUT,                                                                ...
      '%s%s\n',                                                              ...
      '|-------------------+------------------',                             ...
      '+--------------------+--------------------'                           ...
    );
   fprintf                                                                   ...
    (                                                                        ...
      STDOUT,                                                                ...
      '%s%s%s%s\n',                                                          ...
      '|  [degrees]        ',                                                ...
      '|  [meters]        ',                                                 ...
      '|  [microArcSeconds] ',                                               ...
      '|   [nanoMeters]'                                                     ...
    );
   fprintf                                                                   ...
    (                                                                        ...
      STDOUT,                                                                ...
      '%s%s\n',                                                              ...
      '--------------------+------------------',                             ...
      '+--------------------+--------------------'                           ...
    );
%-------------------------------------------------------------------------------
   return;
%}------------------------------------------------------------------------------
