function                                                                     ...
generateConvertGeodeticToEcefUsageMessage(  )
%{------------------------------------------------------------------------------
   STDOUT = 1;
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   fprintf                                                                   ...
   (                                                                         ...
     STDOUT,                                                                 ...
     [                                                                       ...
       '\n\n\n'                                                              ...
       '%s%s\n'                                                              ...
       '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                            ...
       '%s\n%s\n%s\n%s\n%s\n%s\n'                                            ...
       '%s%s\n'                                                              ...
       '\n\n\n'                                                              ...
     ],                                                                      ...
     '====================================================================', ...
     '===========',                                                          ...
     '|',                                                                    ...
     '|  USAGE:',                                                            ...
     '|',                                                                    ...
     '|    [                                                  ...',          ...
     '|      xRectangularMeters,                              ...',          ...
     '|      yRectangularMeters,                              ...',          ...
     '|      zRectangularMeters                               ...',          ...
     '|    ] = convertGeodeticToEcef                          ...',          ...
     '|               (                                       ...',          ...
     '|                 earthEquatorialRadiusMeters,          ...',          ...
     '|                 earthEllipsoidalEccentricitySquared,  ...',          ...
     '|                 geodeticNorthLatitudeRadians,         ...',          ...
     '|                 geocentricEastLongitudeRadians,       ...',          ...
     '|                 geodeticAltitudeMeters                ...',          ...
     '|               );',                                                   ...
     '|',                                                                    ...
     '====================================================================', ...
     '==========='                                                           ...
   );
%------------------------------------------------------------------------------- 
   return;
%}------------------------------------------------------------------------------
